### PR TITLE
Update pullapprove owners

### PR DESCRIPTION
**Pull request by jbabichjapan**
Adding team members to pullapprove approvers

### CODE REVIEW

**Comment by brandonblack** [comment]
👍

**Comment by jaakko-sf** [comment]
Before we can merge, since @brandonblack is not a collaborator, it breaks pullapprove. Would you please update this PR to remove his from the .pullapprove.yml file? :-(

**Comment by brandonblack** [comment]
👍

**Comment by brandonblack** [comment]
@jaakko-sf looking at the config on pull approve, I think if give a 👍 comment it'll sort itself out.

**Comment by jaakko-sf** [comment]
@brandonblack turns out that a validation error is thrown by pullapprove when a GH username is included that is not part of the team. Hence, the update so that when that is merged in we don't land in a similar state

**Pull request closed without merging**
