### PR TITLE
Add back Account entity in Analytics class

### PR DESCRIPTION
**Pull request by Pimentoso**
Upgrading to v6 of the gem broke the option to query for ACCOUNT entity in analytics async jobs, since it was replaced by PROMOTED_ACCOUNT. In my case PROMOTED_ACCOUNT returns empty data so I needed the old option.

This PR enables this usage

```ruby
opts = {
  entity: TwitterAds::Account.name,
  granularity: :total,
  segmentation_type: 'PLATFORMS'
}
TwitterAds::Analytics.create_async_job(account, [account_id], [TwitterAds::Enum::MetricGroup::ENGAGEMENT], opts)
```

### CODE REVIEW

**Comment by tushdante** [comment]
Thanks for making this change @Pimentoso . The correct param name should be `PROMOTED_ACCOUNT` as per our [documentation](https://developer.twitter.com/en/docs/ads/analytics/api-reference/asynchronous)

**Comment by Pimentoso** [comment]
@tushdante can you elaborate? As per documentation the valid entity values are
```ACCOUNT, CAMPAIGN, FUNDING_INSTRUMENT, LINE_ITEM, ORGANIC_TWEET, PROMOTED_ACCOUNT, PROMOTED_TWEET, MEDIA_CREATIVE```

**Comment by tushdante** [comment]
Oops my mistake. Approved!

**Comment by Pimentoso** [comment]
Bump for a merge!

**Comment by Pimentoso** [comment]
Bump again guys, I still need this change after the upgrade to API v8

**Comment by tushdante** [comment]
Apologies for the delay! Merging and closing this out.

**Pull request merged**
