### PR TITLE
Updating enum.rb to include the new VIEW_3S_100PCT BidUnit

### PR DESCRIPTION
**Pull request by msbukkuri**
**Issue Type:** Feature

**Fixes / Relates To:** https://www.apichangelog.com/changes/984bf4bd-3f81-4b38-bec0-04064692c5ba

**Changes Included:**
- Extends the bid_unit to include VIEW_3S_100PCT enumeration value

**DETAILS**
Updating the enum.rb to bring it to current: https://www.apichangelog.com/changes/984bf4bd-3f81-4b38-bec0-04064692c5ba

@brandonblack => In addition to this change, does it make sense to extend this enum to include all of https://dev.twitter.com/ads/basics/enums? Let me know your thoughts.

### CODE REVIEW

**Comment by msbukkuri** [comment]
@houndci-bot updated to change to single quotes.

**Comment by msbukkuri** [comment]
@brandonblack  => In addition to this change, does it make sense to extend this enum to include all of https://dev.twitter.com/ads/basics/enums? Let me know your thoughts.

**Comment by brandonblack** [comment]
@msbukkuri thanks for the contribution. Please update your branch to get the tests passing again.

**Comment by msbukkuri** [comment]
@brandonblack thanks for the quick response. Updated the branch => waiting for tests to pass. Will resolve and update.

**Comment by msbukkuri** [comment]
@brandonblack => In addition to this change, does it make sense to extend this enum to include all of https://dev.twitter.com/ads/basics/enums? Let me know your thoughts.

**Comment by brandonblack** [comment]
Thanks! 👍

**Pull request merged**
