### PR TITLE
include analytics to campaign

### PR DESCRIPTION
**Pull request by kambayashia**
**Issue Type:**
- Feature

**Fixes / Relates To:**

**Changes Included:**

- add analytics to campaign
 - `TwitterAds::Campaign.stats(account, campaignIds, metric_groups, opts)`

**Check List:**

- [ ] Includes adequate test [coverage](https://github.com/twitterdev/twitter-ruby-ads-sdk/tree/master/spec) for changes made.
- [ ] Includes new or updated [documentation](http://twitterdev.github.io/twitter-ruby-ads-sdk/reference/index.html).
- [ ] Includes new or updated usage [examples](https://github.com/twitterdev/twitter-ruby-ads-sdk/tree/master/examples).

_For more information on check list items, please see the [Contributors Guide](https://github.com/twitterdev/twitter-ruby-ads-sdk/tree/master/CONTRIBUTING.md)._

### CODE REVIEW

**Comment by jbabichjapan** [comment]
Thanks - we actually were trying to leave campaign stats off to encourage users to pull Line Item and aggregate on DB side to add up to campaign stats, let me discuss this internally!

**Comment by igniting** [comment]
Any updates on this? If twitter ads api allows to fetch campaign level stats, why not include in the sdk?

**Comment by brandonblack** [comment]
@igniting @kambayashia this issue should probably just be closed. 

As @jbabichjapan already pointed out, it was a deliberate design decision to not support pulling analytics on the campaign or account level. [Best practices](https://dev.twitter.com/ads/analytics/best-practices) and the rate limits on the API strongly favor pulling analytics on the promoted tweet or line item level and we've built all the SDKs to enforce that desired behavior.

>Do request data (ideally) at the line_items and promoted_tweets level, as you can always aggregate and roll these metrics up to get totals across the entire ads entity hierarchy (i.e. for the campaign, funding instrument or account levels).

**Comment by jaakko-sf** [comment]
Approved, as this is part of the endpoints, we should support

**Pull request merged**
